a=int(input())
b=int(input())
c=int(input())
s = str(a*b*c)
print(s.count('0'))
print(s.count('1'))
print(s.count('2'))
print(s.count('3'))
print(s.count('4'))
print(s.count('5'))
print(s.count('6'))
print(s.count('7'))
print(s.count('8'))
print(s.count('9'))